# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ${controller_name}_joint_trajectory_controller

  ${controller_name}_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ${name}_joint1
      - ${name}_joint2
      - ${name}_joint3
      - ${name}_joint4
      - ${name}_joint5
      - ${name}_joint6
      - ${name}_joint7
