controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ${controller_name}_controller:
      type: position_controllers/GripperActionController

${controller_name}_controller:
  ros__parameters:
    default: true
    joint: ${name}_finger_joint1
    allow_stalling: true
